Plutus requires deriving-aeson >= 0.2.3 for the cost model data to load correctly.
On v0.2.2 it throws:

```

src/Language/PlutusCore/Evaluation/Machine/ExBudgetingDefaults.hs:9:6: error:
    • Error in $['add_integer'].type: parsing Integer failed, expected Number, but encountered String
    • In the Template Haskell splice
        $$(readJSONFromFile "language-plutus-core/src/costModel.json")
      In the expression:
        $$(readJSONFromFile "language-plutus-core/src/costModel.json")
      In an equation for ‘defaultCostModel’:
          defaultCostModel
            = $$(readJSONFromFile "language-plutus-core/src/costModel.json")
```